### ISSUE TITLE
Remove the Util Service

### ISSUE THREAD

**Issue by danrot** [massiveart/husky#566]
Currently there is a util service, and I don't really see its point. It could be used standalone as a require js component, but it would make sense to only use the aura extension, which leverages all these functions instead, because these functions should be so common that they are used by almost all components. Because of this it would be redundant to include them via require every time.

The only use case that might make sense, use it in aura extensions, does not work, because we get an error during the build.

**Comment by danrot** [comment]
Realized during https://github.com/massiveart/husky/commit/9f17327fbd0ede0369e36969273f94dd76026377, which is required for https://github.com/sulu-io/sulu/commit/2b71ef3dfe9f59ae332988d34955a34aaef56028
/cc @wachterjohannes

**Comment by wachterjohannes** [comment]
@danrot we should provide both! because we have normal requirejs components which does not use aura itself. for them it would be nice to have most of the functions also available. so for me its no option to remove this service. but we should hold them mostly the same.

**Comment by wachterjohannes** [comment]
for me the util extension should look like this:

```
/**
 * Provides the util function into a sandbox.
 */
define(['services/husky/util'], function(Util) {

    'use strict';

    return {
        name: 'Util',

        initialize: function(app) {
            app.core.util = Util;
        }
    };
});
```

**Comment by wachterjohannes** [comment]
we could also use this services to combine functionality for components and his data- type like i have done it in the PR https://github.com/massiveart/husky/pull/562 with the url-validator.

**Comment by danrot** [comment]
Ok, if we structure the extension like this it is ok for me, but as it is currently it is not acceptable.
