### ISSUE TITLE
Autocomplete dropdown is too long if used in an overlay

### ISSUE THREAD

**Issue by sabinebaer** [massiveart/husky#667]
<img width="779" alt="autocomplete-overlay" src="https://cloud.githubusercontent.com/assets/5627878/16517156/48989cb6-3f7c-11e6-8add-4df348f5498a.png">

**Comment by marcelmoosbrugger** [comment]
It seems that the specific configuration is the problem. However I added a working demo (overlay with autocomplete) in https://github.com/massiveart/husky/pull/669
