### ISSUE TITLE
UrlValidator on null throws uncaught TypeError

### ISSUE THREAD

**Issue by reflexxion** [massiveart/husky#747]
Using the `url-input` component with an initial `null` value throws uncaught `TypeError`.
In [line 88 of url-validator.js](https://github.com/massiveart/husky/blob/develop/husky_services/url-validator.js#L88)

`url` should be checked before calling match on it.

**Comment by danrot** [comment]
@reflexxion Just for me to understand: That's happening on something you've built on your own, not in a standard form delivered with Sulu?

**Comment by reflexxion** [comment]
Thats correct.
Just used the "url" type in sulu structure.
